spring:
  application:
    name: spring
  profiles:
    active: development

springdoc.api-docs.enabled: false

management.endpoints.web.exposure.include: "*"
#management.endpoint.health.show-details: always